CREATE TABLE IF NOT EXISTS public.review (
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    review_text character varying NOT NULL,
    review_date timestamp with time zone DEFAULT now() NOT NULL,
    inv_id integer NOT NULL,
    account_id integer NOT NULL,
    CONSTRAINT review_pkey PRIMARY KEY (review_id) 
    FOREIGN KEY (inv_id) REFERENCES public.inventory (inv_id),
    FOREIGN KEY (account_id) REFERENCES public.account (account_id)
);